/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// SupportFetchCategories struct for SupportFetchCategories
type SupportFetchCategories struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewSupportFetchCategories instantiates a new SupportFetchCategories object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportFetchCategories() *SupportFetchCategories {
	this := SupportFetchCategories{}
	return &this
}

// NewSupportFetchCategoriesWithDefaults instantiates a new SupportFetchCategories object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportFetchCategoriesWithDefaults() *SupportFetchCategories {
	this := SupportFetchCategories{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *SupportFetchCategories) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportFetchCategories) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *SupportFetchCategories) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *SupportFetchCategories) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *SupportFetchCategories) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportFetchCategories) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *SupportFetchCategories) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *SupportFetchCategories) SetPassword(v string) {
	o.Password = &v
}

func (o SupportFetchCategories) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableSupportFetchCategories struct {
	value *SupportFetchCategories
	isSet bool
}

func (v NullableSupportFetchCategories) Get() *SupportFetchCategories {
	return v.value
}

func (v *NullableSupportFetchCategories) Set(val *SupportFetchCategories) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportFetchCategories) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportFetchCategories) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportFetchCategories(val *SupportFetchCategories) *NullableSupportFetchCategories {
	return &NullableSupportFetchCategories{value: val, isSet: true}
}

func (v NullableSupportFetchCategories) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportFetchCategories) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


