/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// FailoverCallRemote2 struct for FailoverCallRemote2
type FailoverCallRemote2 struct {
	Timeout *int32 `json:"timeout,omitempty"`
	Job *bool `json:"job,omitempty"`
	JobReturn NullableBool `json:"job_return,omitempty"`
	Callback *AnyOfstringintegerbooleanobject `json:"callback,omitempty"`
}

// NewFailoverCallRemote2 instantiates a new FailoverCallRemote2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFailoverCallRemote2() *FailoverCallRemote2 {
	this := FailoverCallRemote2{}
	return &this
}

// NewFailoverCallRemote2WithDefaults instantiates a new FailoverCallRemote2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFailoverCallRemote2WithDefaults() *FailoverCallRemote2 {
	this := FailoverCallRemote2{}
	return &this
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *FailoverCallRemote2) GetTimeout() int32 {
	if o == nil || o.Timeout == nil {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FailoverCallRemote2) GetTimeoutOk() (*int32, bool) {
	if o == nil || o.Timeout == nil {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *FailoverCallRemote2) HasTimeout() bool {
	if o != nil && o.Timeout != nil {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *FailoverCallRemote2) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *FailoverCallRemote2) GetJob() bool {
	if o == nil || o.Job == nil {
		var ret bool
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FailoverCallRemote2) GetJobOk() (*bool, bool) {
	if o == nil || o.Job == nil {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *FailoverCallRemote2) HasJob() bool {
	if o != nil && o.Job != nil {
		return true
	}

	return false
}

// SetJob gets a reference to the given bool and assigns it to the Job field.
func (o *FailoverCallRemote2) SetJob(v bool) {
	o.Job = &v
}

// GetJobReturn returns the JobReturn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FailoverCallRemote2) GetJobReturn() bool {
	if o == nil || o.JobReturn.Get() == nil {
		var ret bool
		return ret
	}
	return *o.JobReturn.Get()
}

// GetJobReturnOk returns a tuple with the JobReturn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FailoverCallRemote2) GetJobReturnOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.JobReturn.Get(), o.JobReturn.IsSet()
}

// HasJobReturn returns a boolean if a field has been set.
func (o *FailoverCallRemote2) HasJobReturn() bool {
	if o != nil && o.JobReturn.IsSet() {
		return true
	}

	return false
}

// SetJobReturn gets a reference to the given NullableBool and assigns it to the JobReturn field.
func (o *FailoverCallRemote2) SetJobReturn(v bool) {
	o.JobReturn.Set(&v)
}
// SetJobReturnNil sets the value for JobReturn to be an explicit nil
func (o *FailoverCallRemote2) SetJobReturnNil() {
	o.JobReturn.Set(nil)
}

// UnsetJobReturn ensures that no value is present for JobReturn, not even an explicit nil
func (o *FailoverCallRemote2) UnsetJobReturn() {
	o.JobReturn.Unset()
}

// GetCallback returns the Callback field value if set, zero value otherwise.
func (o *FailoverCallRemote2) GetCallback() AnyOfstringintegerbooleanobject {
	if o == nil || o.Callback == nil {
		var ret AnyOfstringintegerbooleanobject
		return ret
	}
	return *o.Callback
}

// GetCallbackOk returns a tuple with the Callback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FailoverCallRemote2) GetCallbackOk() (*AnyOfstringintegerbooleanobject, bool) {
	if o == nil || o.Callback == nil {
		return nil, false
	}
	return o.Callback, true
}

// HasCallback returns a boolean if a field has been set.
func (o *FailoverCallRemote2) HasCallback() bool {
	if o != nil && o.Callback != nil {
		return true
	}

	return false
}

// SetCallback gets a reference to the given AnyOfstringintegerbooleanobject and assigns it to the Callback field.
func (o *FailoverCallRemote2) SetCallback(v AnyOfstringintegerbooleanobject) {
	o.Callback = &v
}

func (o FailoverCallRemote2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Timeout != nil {
		toSerialize["timeout"] = o.Timeout
	}
	if o.Job != nil {
		toSerialize["job"] = o.Job
	}
	if o.JobReturn.IsSet() {
		toSerialize["job_return"] = o.JobReturn.Get()
	}
	if o.Callback != nil {
		toSerialize["callback"] = o.Callback
	}
	return json.Marshal(toSerialize)
}

type NullableFailoverCallRemote2 struct {
	value *FailoverCallRemote2
	isSet bool
}

func (v NullableFailoverCallRemote2) Get() *FailoverCallRemote2 {
	return v.value
}

func (v *NullableFailoverCallRemote2) Set(val *FailoverCallRemote2) {
	v.value = val
	v.isSet = true
}

func (v NullableFailoverCallRemote2) IsSet() bool {
	return v.isSet
}

func (v *NullableFailoverCallRemote2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFailoverCallRemote2(val *FailoverCallRemote2) *NullableFailoverCallRemote2 {
	return &NullableFailoverCallRemote2{value: val, isSet: true}
}

func (v NullableFailoverCallRemote2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFailoverCallRemote2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


