/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// SystemGeneralUpdate0 struct for SystemGeneralUpdate0
type SystemGeneralUpdate0 struct {
	UiCertificate NullableInt32 `json:"ui_certificate,omitempty"`
	UiHttpsport *int32 `json:"ui_httpsport,omitempty"`
	UiHttpsredirect *bool `json:"ui_httpsredirect,omitempty"`
	UiHttpsprotocols *[]string `json:"ui_httpsprotocols,omitempty"`
	UiPort *int32 `json:"ui_port,omitempty"`
	UiAddress *[]string `json:"ui_address,omitempty"`
	UiV6address *[]string `json:"ui_v6address,omitempty"`
	Kbdmap *string `json:"kbdmap,omitempty"`
	Language *string `json:"language,omitempty"`
	Sysloglevel *string `json:"sysloglevel,omitempty"`
	Syslogserver *string `json:"syslogserver,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
	CrashReporting NullableBool `json:"crash_reporting,omitempty"`
	UsageCollection NullableBool `json:"usage_collection,omitempty"`
}

// NewSystemGeneralUpdate0 instantiates a new SystemGeneralUpdate0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemGeneralUpdate0() *SystemGeneralUpdate0 {
	this := SystemGeneralUpdate0{}
	return &this
}

// NewSystemGeneralUpdate0WithDefaults instantiates a new SystemGeneralUpdate0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemGeneralUpdate0WithDefaults() *SystemGeneralUpdate0 {
	this := SystemGeneralUpdate0{}
	return &this
}

// GetUiCertificate returns the UiCertificate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemGeneralUpdate0) GetUiCertificate() int32 {
	if o == nil || o.UiCertificate.Get() == nil {
		var ret int32
		return ret
	}
	return *o.UiCertificate.Get()
}

// GetUiCertificateOk returns a tuple with the UiCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemGeneralUpdate0) GetUiCertificateOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.UiCertificate.Get(), o.UiCertificate.IsSet()
}

// HasUiCertificate returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUiCertificate() bool {
	if o != nil && o.UiCertificate.IsSet() {
		return true
	}

	return false
}

// SetUiCertificate gets a reference to the given NullableInt32 and assigns it to the UiCertificate field.
func (o *SystemGeneralUpdate0) SetUiCertificate(v int32) {
	o.UiCertificate.Set(&v)
}
// SetUiCertificateNil sets the value for UiCertificate to be an explicit nil
func (o *SystemGeneralUpdate0) SetUiCertificateNil() {
	o.UiCertificate.Set(nil)
}

// UnsetUiCertificate ensures that no value is present for UiCertificate, not even an explicit nil
func (o *SystemGeneralUpdate0) UnsetUiCertificate() {
	o.UiCertificate.Unset()
}

// GetUiHttpsport returns the UiHttpsport field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetUiHttpsport() int32 {
	if o == nil || o.UiHttpsport == nil {
		var ret int32
		return ret
	}
	return *o.UiHttpsport
}

// GetUiHttpsportOk returns a tuple with the UiHttpsport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetUiHttpsportOk() (*int32, bool) {
	if o == nil || o.UiHttpsport == nil {
		return nil, false
	}
	return o.UiHttpsport, true
}

// HasUiHttpsport returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUiHttpsport() bool {
	if o != nil && o.UiHttpsport != nil {
		return true
	}

	return false
}

// SetUiHttpsport gets a reference to the given int32 and assigns it to the UiHttpsport field.
func (o *SystemGeneralUpdate0) SetUiHttpsport(v int32) {
	o.UiHttpsport = &v
}

// GetUiHttpsredirect returns the UiHttpsredirect field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetUiHttpsredirect() bool {
	if o == nil || o.UiHttpsredirect == nil {
		var ret bool
		return ret
	}
	return *o.UiHttpsredirect
}

// GetUiHttpsredirectOk returns a tuple with the UiHttpsredirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetUiHttpsredirectOk() (*bool, bool) {
	if o == nil || o.UiHttpsredirect == nil {
		return nil, false
	}
	return o.UiHttpsredirect, true
}

// HasUiHttpsredirect returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUiHttpsredirect() bool {
	if o != nil && o.UiHttpsredirect != nil {
		return true
	}

	return false
}

// SetUiHttpsredirect gets a reference to the given bool and assigns it to the UiHttpsredirect field.
func (o *SystemGeneralUpdate0) SetUiHttpsredirect(v bool) {
	o.UiHttpsredirect = &v
}

// GetUiHttpsprotocols returns the UiHttpsprotocols field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetUiHttpsprotocols() []string {
	if o == nil || o.UiHttpsprotocols == nil {
		var ret []string
		return ret
	}
	return *o.UiHttpsprotocols
}

// GetUiHttpsprotocolsOk returns a tuple with the UiHttpsprotocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetUiHttpsprotocolsOk() (*[]string, bool) {
	if o == nil || o.UiHttpsprotocols == nil {
		return nil, false
	}
	return o.UiHttpsprotocols, true
}

// HasUiHttpsprotocols returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUiHttpsprotocols() bool {
	if o != nil && o.UiHttpsprotocols != nil {
		return true
	}

	return false
}

// SetUiHttpsprotocols gets a reference to the given []string and assigns it to the UiHttpsprotocols field.
func (o *SystemGeneralUpdate0) SetUiHttpsprotocols(v []string) {
	o.UiHttpsprotocols = &v
}

// GetUiPort returns the UiPort field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetUiPort() int32 {
	if o == nil || o.UiPort == nil {
		var ret int32
		return ret
	}
	return *o.UiPort
}

// GetUiPortOk returns a tuple with the UiPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetUiPortOk() (*int32, bool) {
	if o == nil || o.UiPort == nil {
		return nil, false
	}
	return o.UiPort, true
}

// HasUiPort returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUiPort() bool {
	if o != nil && o.UiPort != nil {
		return true
	}

	return false
}

// SetUiPort gets a reference to the given int32 and assigns it to the UiPort field.
func (o *SystemGeneralUpdate0) SetUiPort(v int32) {
	o.UiPort = &v
}

// GetUiAddress returns the UiAddress field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetUiAddress() []string {
	if o == nil || o.UiAddress == nil {
		var ret []string
		return ret
	}
	return *o.UiAddress
}

// GetUiAddressOk returns a tuple with the UiAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetUiAddressOk() (*[]string, bool) {
	if o == nil || o.UiAddress == nil {
		return nil, false
	}
	return o.UiAddress, true
}

// HasUiAddress returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUiAddress() bool {
	if o != nil && o.UiAddress != nil {
		return true
	}

	return false
}

// SetUiAddress gets a reference to the given []string and assigns it to the UiAddress field.
func (o *SystemGeneralUpdate0) SetUiAddress(v []string) {
	o.UiAddress = &v
}

// GetUiV6address returns the UiV6address field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetUiV6address() []string {
	if o == nil || o.UiV6address == nil {
		var ret []string
		return ret
	}
	return *o.UiV6address
}

// GetUiV6addressOk returns a tuple with the UiV6address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetUiV6addressOk() (*[]string, bool) {
	if o == nil || o.UiV6address == nil {
		return nil, false
	}
	return o.UiV6address, true
}

// HasUiV6address returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUiV6address() bool {
	if o != nil && o.UiV6address != nil {
		return true
	}

	return false
}

// SetUiV6address gets a reference to the given []string and assigns it to the UiV6address field.
func (o *SystemGeneralUpdate0) SetUiV6address(v []string) {
	o.UiV6address = &v
}

// GetKbdmap returns the Kbdmap field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetKbdmap() string {
	if o == nil || o.Kbdmap == nil {
		var ret string
		return ret
	}
	return *o.Kbdmap
}

// GetKbdmapOk returns a tuple with the Kbdmap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetKbdmapOk() (*string, bool) {
	if o == nil || o.Kbdmap == nil {
		return nil, false
	}
	return o.Kbdmap, true
}

// HasKbdmap returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasKbdmap() bool {
	if o != nil && o.Kbdmap != nil {
		return true
	}

	return false
}

// SetKbdmap gets a reference to the given string and assigns it to the Kbdmap field.
func (o *SystemGeneralUpdate0) SetKbdmap(v string) {
	o.Kbdmap = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetLanguage() string {
	if o == nil || o.Language == nil {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetLanguageOk() (*string, bool) {
	if o == nil || o.Language == nil {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasLanguage() bool {
	if o != nil && o.Language != nil {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *SystemGeneralUpdate0) SetLanguage(v string) {
	o.Language = &v
}

// GetSysloglevel returns the Sysloglevel field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetSysloglevel() string {
	if o == nil || o.Sysloglevel == nil {
		var ret string
		return ret
	}
	return *o.Sysloglevel
}

// GetSysloglevelOk returns a tuple with the Sysloglevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetSysloglevelOk() (*string, bool) {
	if o == nil || o.Sysloglevel == nil {
		return nil, false
	}
	return o.Sysloglevel, true
}

// HasSysloglevel returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasSysloglevel() bool {
	if o != nil && o.Sysloglevel != nil {
		return true
	}

	return false
}

// SetSysloglevel gets a reference to the given string and assigns it to the Sysloglevel field.
func (o *SystemGeneralUpdate0) SetSysloglevel(v string) {
	o.Sysloglevel = &v
}

// GetSyslogserver returns the Syslogserver field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetSyslogserver() string {
	if o == nil || o.Syslogserver == nil {
		var ret string
		return ret
	}
	return *o.Syslogserver
}

// GetSyslogserverOk returns a tuple with the Syslogserver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetSyslogserverOk() (*string, bool) {
	if o == nil || o.Syslogserver == nil {
		return nil, false
	}
	return o.Syslogserver, true
}

// HasSyslogserver returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasSyslogserver() bool {
	if o != nil && o.Syslogserver != nil {
		return true
	}

	return false
}

// SetSyslogserver gets a reference to the given string and assigns it to the Syslogserver field.
func (o *SystemGeneralUpdate0) SetSyslogserver(v string) {
	o.Syslogserver = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *SystemGeneralUpdate0) GetTimezone() string {
	if o == nil || o.Timezone == nil {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemGeneralUpdate0) GetTimezoneOk() (*string, bool) {
	if o == nil || o.Timezone == nil {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasTimezone() bool {
	if o != nil && o.Timezone != nil {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *SystemGeneralUpdate0) SetTimezone(v string) {
	o.Timezone = &v
}

// GetCrashReporting returns the CrashReporting field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemGeneralUpdate0) GetCrashReporting() bool {
	if o == nil || o.CrashReporting.Get() == nil {
		var ret bool
		return ret
	}
	return *o.CrashReporting.Get()
}

// GetCrashReportingOk returns a tuple with the CrashReporting field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemGeneralUpdate0) GetCrashReportingOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CrashReporting.Get(), o.CrashReporting.IsSet()
}

// HasCrashReporting returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasCrashReporting() bool {
	if o != nil && o.CrashReporting.IsSet() {
		return true
	}

	return false
}

// SetCrashReporting gets a reference to the given NullableBool and assigns it to the CrashReporting field.
func (o *SystemGeneralUpdate0) SetCrashReporting(v bool) {
	o.CrashReporting.Set(&v)
}
// SetCrashReportingNil sets the value for CrashReporting to be an explicit nil
func (o *SystemGeneralUpdate0) SetCrashReportingNil() {
	o.CrashReporting.Set(nil)
}

// UnsetCrashReporting ensures that no value is present for CrashReporting, not even an explicit nil
func (o *SystemGeneralUpdate0) UnsetCrashReporting() {
	o.CrashReporting.Unset()
}

// GetUsageCollection returns the UsageCollection field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemGeneralUpdate0) GetUsageCollection() bool {
	if o == nil || o.UsageCollection.Get() == nil {
		var ret bool
		return ret
	}
	return *o.UsageCollection.Get()
}

// GetUsageCollectionOk returns a tuple with the UsageCollection field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemGeneralUpdate0) GetUsageCollectionOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.UsageCollection.Get(), o.UsageCollection.IsSet()
}

// HasUsageCollection returns a boolean if a field has been set.
func (o *SystemGeneralUpdate0) HasUsageCollection() bool {
	if o != nil && o.UsageCollection.IsSet() {
		return true
	}

	return false
}

// SetUsageCollection gets a reference to the given NullableBool and assigns it to the UsageCollection field.
func (o *SystemGeneralUpdate0) SetUsageCollection(v bool) {
	o.UsageCollection.Set(&v)
}
// SetUsageCollectionNil sets the value for UsageCollection to be an explicit nil
func (o *SystemGeneralUpdate0) SetUsageCollectionNil() {
	o.UsageCollection.Set(nil)
}

// UnsetUsageCollection ensures that no value is present for UsageCollection, not even an explicit nil
func (o *SystemGeneralUpdate0) UnsetUsageCollection() {
	o.UsageCollection.Unset()
}

func (o SystemGeneralUpdate0) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UiCertificate.IsSet() {
		toSerialize["ui_certificate"] = o.UiCertificate.Get()
	}
	if o.UiHttpsport != nil {
		toSerialize["ui_httpsport"] = o.UiHttpsport
	}
	if o.UiHttpsredirect != nil {
		toSerialize["ui_httpsredirect"] = o.UiHttpsredirect
	}
	if o.UiHttpsprotocols != nil {
		toSerialize["ui_httpsprotocols"] = o.UiHttpsprotocols
	}
	if o.UiPort != nil {
		toSerialize["ui_port"] = o.UiPort
	}
	if o.UiAddress != nil {
		toSerialize["ui_address"] = o.UiAddress
	}
	if o.UiV6address != nil {
		toSerialize["ui_v6address"] = o.UiV6address
	}
	if o.Kbdmap != nil {
		toSerialize["kbdmap"] = o.Kbdmap
	}
	if o.Language != nil {
		toSerialize["language"] = o.Language
	}
	if o.Sysloglevel != nil {
		toSerialize["sysloglevel"] = o.Sysloglevel
	}
	if o.Syslogserver != nil {
		toSerialize["syslogserver"] = o.Syslogserver
	}
	if o.Timezone != nil {
		toSerialize["timezone"] = o.Timezone
	}
	if o.CrashReporting.IsSet() {
		toSerialize["crash_reporting"] = o.CrashReporting.Get()
	}
	if o.UsageCollection.IsSet() {
		toSerialize["usage_collection"] = o.UsageCollection.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableSystemGeneralUpdate0 struct {
	value *SystemGeneralUpdate0
	isSet bool
}

func (v NullableSystemGeneralUpdate0) Get() *SystemGeneralUpdate0 {
	return v.value
}

func (v *NullableSystemGeneralUpdate0) Set(val *SystemGeneralUpdate0) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemGeneralUpdate0) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemGeneralUpdate0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemGeneralUpdate0(val *SystemGeneralUpdate0) *NullableSystemGeneralUpdate0 {
	return &NullableSystemGeneralUpdate0{value: val, isSet: true}
}

func (v NullableSystemGeneralUpdate0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemGeneralUpdate0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


