/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// FilesystemSetacl0 struct for FilesystemSetacl0
type FilesystemSetacl0 struct {
	Path *string `json:"path,omitempty"`
	Uid NullableInt32 `json:"uid,omitempty"`
	Gid NullableInt32 `json:"gid,omitempty"`
	Dacl *[]OneOfobjectobject `json:"dacl,omitempty"`
	Nfs41Flags *FilesystemSetacl0Nfs41Flags `json:"nfs41_flags,omitempty"`
	Acltype *string `json:"acltype,omitempty"`
	Options *FilesystemSetacl0Options `json:"options,omitempty"`
}

// NewFilesystemSetacl0 instantiates a new FilesystemSetacl0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesystemSetacl0() *FilesystemSetacl0 {
	this := FilesystemSetacl0{}
	return &this
}

// NewFilesystemSetacl0WithDefaults instantiates a new FilesystemSetacl0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesystemSetacl0WithDefaults() *FilesystemSetacl0 {
	this := FilesystemSetacl0{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *FilesystemSetacl0) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *FilesystemSetacl0) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *FilesystemSetacl0) SetPath(v string) {
	o.Path = &v
}

// GetUid returns the Uid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilesystemSetacl0) GetUid() int32 {
	if o == nil || o.Uid.Get() == nil {
		var ret int32
		return ret
	}
	return *o.Uid.Get()
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilesystemSetacl0) GetUidOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Uid.Get(), o.Uid.IsSet()
}

// HasUid returns a boolean if a field has been set.
func (o *FilesystemSetacl0) HasUid() bool {
	if o != nil && o.Uid.IsSet() {
		return true
	}

	return false
}

// SetUid gets a reference to the given NullableInt32 and assigns it to the Uid field.
func (o *FilesystemSetacl0) SetUid(v int32) {
	o.Uid.Set(&v)
}
// SetUidNil sets the value for Uid to be an explicit nil
func (o *FilesystemSetacl0) SetUidNil() {
	o.Uid.Set(nil)
}

// UnsetUid ensures that no value is present for Uid, not even an explicit nil
func (o *FilesystemSetacl0) UnsetUid() {
	o.Uid.Unset()
}

// GetGid returns the Gid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilesystemSetacl0) GetGid() int32 {
	if o == nil || o.Gid.Get() == nil {
		var ret int32
		return ret
	}
	return *o.Gid.Get()
}

// GetGidOk returns a tuple with the Gid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilesystemSetacl0) GetGidOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Gid.Get(), o.Gid.IsSet()
}

// HasGid returns a boolean if a field has been set.
func (o *FilesystemSetacl0) HasGid() bool {
	if o != nil && o.Gid.IsSet() {
		return true
	}

	return false
}

// SetGid gets a reference to the given NullableInt32 and assigns it to the Gid field.
func (o *FilesystemSetacl0) SetGid(v int32) {
	o.Gid.Set(&v)
}
// SetGidNil sets the value for Gid to be an explicit nil
func (o *FilesystemSetacl0) SetGidNil() {
	o.Gid.Set(nil)
}

// UnsetGid ensures that no value is present for Gid, not even an explicit nil
func (o *FilesystemSetacl0) UnsetGid() {
	o.Gid.Unset()
}

// GetDacl returns the Dacl field value if set, zero value otherwise.
func (o *FilesystemSetacl0) GetDacl() []OneOfobjectobject {
	if o == nil || o.Dacl == nil {
		var ret []OneOfobjectobject
		return ret
	}
	return *o.Dacl
}

// GetDaclOk returns a tuple with the Dacl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0) GetDaclOk() (*[]OneOfobjectobject, bool) {
	if o == nil || o.Dacl == nil {
		return nil, false
	}
	return o.Dacl, true
}

// HasDacl returns a boolean if a field has been set.
func (o *FilesystemSetacl0) HasDacl() bool {
	if o != nil && o.Dacl != nil {
		return true
	}

	return false
}

// SetDacl gets a reference to the given []OneOfobjectobject and assigns it to the Dacl field.
func (o *FilesystemSetacl0) SetDacl(v []OneOfobjectobject) {
	o.Dacl = &v
}

// GetNfs41Flags returns the Nfs41Flags field value if set, zero value otherwise.
func (o *FilesystemSetacl0) GetNfs41Flags() FilesystemSetacl0Nfs41Flags {
	if o == nil || o.Nfs41Flags == nil {
		var ret FilesystemSetacl0Nfs41Flags
		return ret
	}
	return *o.Nfs41Flags
}

// GetNfs41FlagsOk returns a tuple with the Nfs41Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0) GetNfs41FlagsOk() (*FilesystemSetacl0Nfs41Flags, bool) {
	if o == nil || o.Nfs41Flags == nil {
		return nil, false
	}
	return o.Nfs41Flags, true
}

// HasNfs41Flags returns a boolean if a field has been set.
func (o *FilesystemSetacl0) HasNfs41Flags() bool {
	if o != nil && o.Nfs41Flags != nil {
		return true
	}

	return false
}

// SetNfs41Flags gets a reference to the given FilesystemSetacl0Nfs41Flags and assigns it to the Nfs41Flags field.
func (o *FilesystemSetacl0) SetNfs41Flags(v FilesystemSetacl0Nfs41Flags) {
	o.Nfs41Flags = &v
}

// GetAcltype returns the Acltype field value if set, zero value otherwise.
func (o *FilesystemSetacl0) GetAcltype() string {
	if o == nil || o.Acltype == nil {
		var ret string
		return ret
	}
	return *o.Acltype
}

// GetAcltypeOk returns a tuple with the Acltype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0) GetAcltypeOk() (*string, bool) {
	if o == nil || o.Acltype == nil {
		return nil, false
	}
	return o.Acltype, true
}

// HasAcltype returns a boolean if a field has been set.
func (o *FilesystemSetacl0) HasAcltype() bool {
	if o != nil && o.Acltype != nil {
		return true
	}

	return false
}

// SetAcltype gets a reference to the given string and assigns it to the Acltype field.
func (o *FilesystemSetacl0) SetAcltype(v string) {
	o.Acltype = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *FilesystemSetacl0) GetOptions() FilesystemSetacl0Options {
	if o == nil || o.Options == nil {
		var ret FilesystemSetacl0Options
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0) GetOptionsOk() (*FilesystemSetacl0Options, bool) {
	if o == nil || o.Options == nil {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *FilesystemSetacl0) HasOptions() bool {
	if o != nil && o.Options != nil {
		return true
	}

	return false
}

// SetOptions gets a reference to the given FilesystemSetacl0Options and assigns it to the Options field.
func (o *FilesystemSetacl0) SetOptions(v FilesystemSetacl0Options) {
	o.Options = &v
}

func (o FilesystemSetacl0) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.Uid.IsSet() {
		toSerialize["uid"] = o.Uid.Get()
	}
	if o.Gid.IsSet() {
		toSerialize["gid"] = o.Gid.Get()
	}
	if o.Dacl != nil {
		toSerialize["dacl"] = o.Dacl
	}
	if o.Nfs41Flags != nil {
		toSerialize["nfs41_flags"] = o.Nfs41Flags
	}
	if o.Acltype != nil {
		toSerialize["acltype"] = o.Acltype
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableFilesystemSetacl0 struct {
	value *FilesystemSetacl0
	isSet bool
}

func (v NullableFilesystemSetacl0) Get() *FilesystemSetacl0 {
	return v.value
}

func (v *NullableFilesystemSetacl0) Set(val *FilesystemSetacl0) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesystemSetacl0) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesystemSetacl0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesystemSetacl0(val *FilesystemSetacl0) *NullableFilesystemSetacl0 {
	return &NullableFilesystemSetacl0{value: val, isSet: true}
}

func (v NullableFilesystemSetacl0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesystemSetacl0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


