/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// PoolSnapshottaskUpdate1 struct for PoolSnapshottaskUpdate1
type PoolSnapshottaskUpdate1 struct {
	Dataset *string `json:"dataset,omitempty"`
	Recursive *bool `json:"recursive,omitempty"`
	Exclude *[]string `json:"exclude,omitempty"`
	LifetimeValue *int32 `json:"lifetime_value,omitempty"`
	LifetimeUnit *string `json:"lifetime_unit,omitempty"`
	NamingSchema *string `json:"naming_schema,omitempty"`
	Schedule *PoolSnapshottaskCreate0Schedule `json:"schedule,omitempty"`
	AllowEmpty *bool `json:"allow_empty,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
}

// NewPoolSnapshottaskUpdate1 instantiates a new PoolSnapshottaskUpdate1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolSnapshottaskUpdate1() *PoolSnapshottaskUpdate1 {
	this := PoolSnapshottaskUpdate1{}
	return &this
}

// NewPoolSnapshottaskUpdate1WithDefaults instantiates a new PoolSnapshottaskUpdate1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolSnapshottaskUpdate1WithDefaults() *PoolSnapshottaskUpdate1 {
	this := PoolSnapshottaskUpdate1{}
	return &this
}

// GetDataset returns the Dataset field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetDataset() string {
	if o == nil || o.Dataset == nil {
		var ret string
		return ret
	}
	return *o.Dataset
}

// GetDatasetOk returns a tuple with the Dataset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetDatasetOk() (*string, bool) {
	if o == nil || o.Dataset == nil {
		return nil, false
	}
	return o.Dataset, true
}

// HasDataset returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasDataset() bool {
	if o != nil && o.Dataset != nil {
		return true
	}

	return false
}

// SetDataset gets a reference to the given string and assigns it to the Dataset field.
func (o *PoolSnapshottaskUpdate1) SetDataset(v string) {
	o.Dataset = &v
}

// GetRecursive returns the Recursive field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetRecursive() bool {
	if o == nil || o.Recursive == nil {
		var ret bool
		return ret
	}
	return *o.Recursive
}

// GetRecursiveOk returns a tuple with the Recursive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetRecursiveOk() (*bool, bool) {
	if o == nil || o.Recursive == nil {
		return nil, false
	}
	return o.Recursive, true
}

// HasRecursive returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasRecursive() bool {
	if o != nil && o.Recursive != nil {
		return true
	}

	return false
}

// SetRecursive gets a reference to the given bool and assigns it to the Recursive field.
func (o *PoolSnapshottaskUpdate1) SetRecursive(v bool) {
	o.Recursive = &v
}

// GetExclude returns the Exclude field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetExclude() []string {
	if o == nil || o.Exclude == nil {
		var ret []string
		return ret
	}
	return *o.Exclude
}

// GetExcludeOk returns a tuple with the Exclude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetExcludeOk() (*[]string, bool) {
	if o == nil || o.Exclude == nil {
		return nil, false
	}
	return o.Exclude, true
}

// HasExclude returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasExclude() bool {
	if o != nil && o.Exclude != nil {
		return true
	}

	return false
}

// SetExclude gets a reference to the given []string and assigns it to the Exclude field.
func (o *PoolSnapshottaskUpdate1) SetExclude(v []string) {
	o.Exclude = &v
}

// GetLifetimeValue returns the LifetimeValue field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetLifetimeValue() int32 {
	if o == nil || o.LifetimeValue == nil {
		var ret int32
		return ret
	}
	return *o.LifetimeValue
}

// GetLifetimeValueOk returns a tuple with the LifetimeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetLifetimeValueOk() (*int32, bool) {
	if o == nil || o.LifetimeValue == nil {
		return nil, false
	}
	return o.LifetimeValue, true
}

// HasLifetimeValue returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasLifetimeValue() bool {
	if o != nil && o.LifetimeValue != nil {
		return true
	}

	return false
}

// SetLifetimeValue gets a reference to the given int32 and assigns it to the LifetimeValue field.
func (o *PoolSnapshottaskUpdate1) SetLifetimeValue(v int32) {
	o.LifetimeValue = &v
}

// GetLifetimeUnit returns the LifetimeUnit field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetLifetimeUnit() string {
	if o == nil || o.LifetimeUnit == nil {
		var ret string
		return ret
	}
	return *o.LifetimeUnit
}

// GetLifetimeUnitOk returns a tuple with the LifetimeUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetLifetimeUnitOk() (*string, bool) {
	if o == nil || o.LifetimeUnit == nil {
		return nil, false
	}
	return o.LifetimeUnit, true
}

// HasLifetimeUnit returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasLifetimeUnit() bool {
	if o != nil && o.LifetimeUnit != nil {
		return true
	}

	return false
}

// SetLifetimeUnit gets a reference to the given string and assigns it to the LifetimeUnit field.
func (o *PoolSnapshottaskUpdate1) SetLifetimeUnit(v string) {
	o.LifetimeUnit = &v
}

// GetNamingSchema returns the NamingSchema field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetNamingSchema() string {
	if o == nil || o.NamingSchema == nil {
		var ret string
		return ret
	}
	return *o.NamingSchema
}

// GetNamingSchemaOk returns a tuple with the NamingSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetNamingSchemaOk() (*string, bool) {
	if o == nil || o.NamingSchema == nil {
		return nil, false
	}
	return o.NamingSchema, true
}

// HasNamingSchema returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasNamingSchema() bool {
	if o != nil && o.NamingSchema != nil {
		return true
	}

	return false
}

// SetNamingSchema gets a reference to the given string and assigns it to the NamingSchema field.
func (o *PoolSnapshottaskUpdate1) SetNamingSchema(v string) {
	o.NamingSchema = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetSchedule() PoolSnapshottaskCreate0Schedule {
	if o == nil || o.Schedule == nil {
		var ret PoolSnapshottaskCreate0Schedule
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetScheduleOk() (*PoolSnapshottaskCreate0Schedule, bool) {
	if o == nil || o.Schedule == nil {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasSchedule() bool {
	if o != nil && o.Schedule != nil {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given PoolSnapshottaskCreate0Schedule and assigns it to the Schedule field.
func (o *PoolSnapshottaskUpdate1) SetSchedule(v PoolSnapshottaskCreate0Schedule) {
	o.Schedule = &v
}

// GetAllowEmpty returns the AllowEmpty field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetAllowEmpty() bool {
	if o == nil || o.AllowEmpty == nil {
		var ret bool
		return ret
	}
	return *o.AllowEmpty
}

// GetAllowEmptyOk returns a tuple with the AllowEmpty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetAllowEmptyOk() (*bool, bool) {
	if o == nil || o.AllowEmpty == nil {
		return nil, false
	}
	return o.AllowEmpty, true
}

// HasAllowEmpty returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasAllowEmpty() bool {
	if o != nil && o.AllowEmpty != nil {
		return true
	}

	return false
}

// SetAllowEmpty gets a reference to the given bool and assigns it to the AllowEmpty field.
func (o *PoolSnapshottaskUpdate1) SetAllowEmpty(v bool) {
	o.AllowEmpty = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PoolSnapshottaskUpdate1) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolSnapshottaskUpdate1) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PoolSnapshottaskUpdate1) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PoolSnapshottaskUpdate1) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o PoolSnapshottaskUpdate1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Dataset != nil {
		toSerialize["dataset"] = o.Dataset
	}
	if o.Recursive != nil {
		toSerialize["recursive"] = o.Recursive
	}
	if o.Exclude != nil {
		toSerialize["exclude"] = o.Exclude
	}
	if o.LifetimeValue != nil {
		toSerialize["lifetime_value"] = o.LifetimeValue
	}
	if o.LifetimeUnit != nil {
		toSerialize["lifetime_unit"] = o.LifetimeUnit
	}
	if o.NamingSchema != nil {
		toSerialize["naming_schema"] = o.NamingSchema
	}
	if o.Schedule != nil {
		toSerialize["schedule"] = o.Schedule
	}
	if o.AllowEmpty != nil {
		toSerialize["allow_empty"] = o.AllowEmpty
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullablePoolSnapshottaskUpdate1 struct {
	value *PoolSnapshottaskUpdate1
	isSet bool
}

func (v NullablePoolSnapshottaskUpdate1) Get() *PoolSnapshottaskUpdate1 {
	return v.value
}

func (v *NullablePoolSnapshottaskUpdate1) Set(val *PoolSnapshottaskUpdate1) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolSnapshottaskUpdate1) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolSnapshottaskUpdate1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolSnapshottaskUpdate1(val *PoolSnapshottaskUpdate1) *NullablePoolSnapshottaskUpdate1 {
	return &NullablePoolSnapshottaskUpdate1{value: val, isSet: true}
}

func (v NullablePoolSnapshottaskUpdate1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolSnapshottaskUpdate1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


