/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
	"fmt"
)

// UserSetAttribute2 struct for UserSetAttribute2
type UserSetAttribute2 struct {
	bool *bool
	int32 *int32
	map[string]interface{} *map[string]interface{}
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UserSetAttribute2) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into bool
	err = json.Unmarshal(data, &dst.bool);
	if err == nil {
		jsonbool, _ := json.Marshal(dst.bool)
		if string(jsonbool) == "{}" { // empty struct
			dst.bool = nil
		} else {
			return nil // data stored in dst.bool, return on the first match
		}
	} else {
		dst.bool = nil
	}

	// try to unmarshal JSON data into int32
	err = json.Unmarshal(data, &dst.int32);
	if err == nil {
		jsonint32, _ := json.Marshal(dst.int32)
		if string(jsonint32) == "{}" { // empty struct
			dst.int32 = nil
		} else {
			return nil // data stored in dst.int32, return on the first match
		}
	} else {
		dst.int32 = nil
	}

	// try to unmarshal JSON data into map[string]interface{}
	err = json.Unmarshal(data, &dst.map[string]interface{});
	if err == nil {
		jsonmap[string]interface{}, _ := json.Marshal(dst.map[string]interface{})
		if string(jsonmap[string]interface{}) == "{}" { // empty struct
			dst.map[string]interface{} = nil
		} else {
			return nil // data stored in dst.map[string]interface{}, return on the first match
		}
	} else {
		dst.map[string]interface{} = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(UserSetAttribute2)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *UserSetAttribute2) MarshalJSON() ([]byte, error) {
	if src.bool != nil {
		return json.Marshal(&src.bool)
	}

	if src.int32 != nil {
		return json.Marshal(&src.int32)
	}

	if src.map[string]interface{} != nil {
		return json.Marshal(&src.map[string]interface{})
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableUserSetAttribute2 struct {
	value *UserSetAttribute2
	isSet bool
}

func (v NullableUserSetAttribute2) Get() *UserSetAttribute2 {
	return v.value
}

func (v *NullableUserSetAttribute2) Set(val *UserSetAttribute2) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSetAttribute2) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSetAttribute2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSetAttribute2(val *UserSetAttribute2) *NullableUserSetAttribute2 {
	return &NullableUserSetAttribute2{value: val, isSet: true}
}

func (v NullableUserSetAttribute2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSetAttribute2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


