/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// PoolAttach struct for PoolAttach
type PoolAttach struct {
	Oid *int32 `json:"oid,omitempty"`
	PoolAttach *PoolAttach1 `json:"pool_attach,omitempty"`
}

// NewPoolAttach instantiates a new PoolAttach object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolAttach() *PoolAttach {
	this := PoolAttach{}
	var poolAttach PoolAttach1 = {}
	this.PoolAttach = &poolAttach
	return &this
}

// NewPoolAttachWithDefaults instantiates a new PoolAttach object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolAttachWithDefaults() *PoolAttach {
	this := PoolAttach{}
	var poolAttach PoolAttach1 = {}
	this.PoolAttach = &poolAttach
	return &this
}

// GetOid returns the Oid field value if set, zero value otherwise.
func (o *PoolAttach) GetOid() int32 {
	if o == nil || o.Oid == nil {
		var ret int32
		return ret
	}
	return *o.Oid
}

// GetOidOk returns a tuple with the Oid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolAttach) GetOidOk() (*int32, bool) {
	if o == nil || o.Oid == nil {
		return nil, false
	}
	return o.Oid, true
}

// HasOid returns a boolean if a field has been set.
func (o *PoolAttach) HasOid() bool {
	if o != nil && o.Oid != nil {
		return true
	}

	return false
}

// SetOid gets a reference to the given int32 and assigns it to the Oid field.
func (o *PoolAttach) SetOid(v int32) {
	o.Oid = &v
}

// GetPoolAttach returns the PoolAttach field value if set, zero value otherwise.
func (o *PoolAttach) GetPoolAttach() PoolAttach1 {
	if o == nil || o.PoolAttach == nil {
		var ret PoolAttach1
		return ret
	}
	return *o.PoolAttach
}

// GetPoolAttachOk returns a tuple with the PoolAttach field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolAttach) GetPoolAttachOk() (*PoolAttach1, bool) {
	if o == nil || o.PoolAttach == nil {
		return nil, false
	}
	return o.PoolAttach, true
}

// HasPoolAttach returns a boolean if a field has been set.
func (o *PoolAttach) HasPoolAttach() bool {
	if o != nil && o.PoolAttach != nil {
		return true
	}

	return false
}

// SetPoolAttach gets a reference to the given PoolAttach1 and assigns it to the PoolAttach field.
func (o *PoolAttach) SetPoolAttach(v PoolAttach1) {
	o.PoolAttach = &v
}

func (o PoolAttach) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Oid != nil {
		toSerialize["oid"] = o.Oid
	}
	if o.PoolAttach != nil {
		toSerialize["pool_attach"] = o.PoolAttach
	}
	return json.Marshal(toSerialize)
}

type NullablePoolAttach struct {
	value *PoolAttach
	isSet bool
}

func (v NullablePoolAttach) Get() *PoolAttach {
	return v.value
}

func (v *NullablePoolAttach) Set(val *PoolAttach) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolAttach) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolAttach) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolAttach(val *PoolAttach) *NullablePoolAttach {
	return &NullablePoolAttach{value: val, isSet: true}
}

func (v NullablePoolAttach) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolAttach) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


