/*
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// FilesystemSetacl0Options struct for FilesystemSetacl0Options
type FilesystemSetacl0Options struct {
	Stripacl *bool `json:"stripacl,omitempty"`
	Recursive *bool `json:"recursive,omitempty"`
	Traverse *bool `json:"traverse,omitempty"`
	Canonicalize *bool `json:"canonicalize,omitempty"`
}

// NewFilesystemSetacl0Options instantiates a new FilesystemSetacl0Options object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesystemSetacl0Options() *FilesystemSetacl0Options {
	this := FilesystemSetacl0Options{}
	return &this
}

// NewFilesystemSetacl0OptionsWithDefaults instantiates a new FilesystemSetacl0Options object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesystemSetacl0OptionsWithDefaults() *FilesystemSetacl0Options {
	this := FilesystemSetacl0Options{}
	return &this
}

// GetStripacl returns the Stripacl field value if set, zero value otherwise.
func (o *FilesystemSetacl0Options) GetStripacl() bool {
	if o == nil || o.Stripacl == nil {
		var ret bool
		return ret
	}
	return *o.Stripacl
}

// GetStripaclOk returns a tuple with the Stripacl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0Options) GetStripaclOk() (*bool, bool) {
	if o == nil || o.Stripacl == nil {
		return nil, false
	}
	return o.Stripacl, true
}

// HasStripacl returns a boolean if a field has been set.
func (o *FilesystemSetacl0Options) HasStripacl() bool {
	if o != nil && o.Stripacl != nil {
		return true
	}

	return false
}

// SetStripacl gets a reference to the given bool and assigns it to the Stripacl field.
func (o *FilesystemSetacl0Options) SetStripacl(v bool) {
	o.Stripacl = &v
}

// GetRecursive returns the Recursive field value if set, zero value otherwise.
func (o *FilesystemSetacl0Options) GetRecursive() bool {
	if o == nil || o.Recursive == nil {
		var ret bool
		return ret
	}
	return *o.Recursive
}

// GetRecursiveOk returns a tuple with the Recursive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0Options) GetRecursiveOk() (*bool, bool) {
	if o == nil || o.Recursive == nil {
		return nil, false
	}
	return o.Recursive, true
}

// HasRecursive returns a boolean if a field has been set.
func (o *FilesystemSetacl0Options) HasRecursive() bool {
	if o != nil && o.Recursive != nil {
		return true
	}

	return false
}

// SetRecursive gets a reference to the given bool and assigns it to the Recursive field.
func (o *FilesystemSetacl0Options) SetRecursive(v bool) {
	o.Recursive = &v
}

// GetTraverse returns the Traverse field value if set, zero value otherwise.
func (o *FilesystemSetacl0Options) GetTraverse() bool {
	if o == nil || o.Traverse == nil {
		var ret bool
		return ret
	}
	return *o.Traverse
}

// GetTraverseOk returns a tuple with the Traverse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0Options) GetTraverseOk() (*bool, bool) {
	if o == nil || o.Traverse == nil {
		return nil, false
	}
	return o.Traverse, true
}

// HasTraverse returns a boolean if a field has been set.
func (o *FilesystemSetacl0Options) HasTraverse() bool {
	if o != nil && o.Traverse != nil {
		return true
	}

	return false
}

// SetTraverse gets a reference to the given bool and assigns it to the Traverse field.
func (o *FilesystemSetacl0Options) SetTraverse(v bool) {
	o.Traverse = &v
}

// GetCanonicalize returns the Canonicalize field value if set, zero value otherwise.
func (o *FilesystemSetacl0Options) GetCanonicalize() bool {
	if o == nil || o.Canonicalize == nil {
		var ret bool
		return ret
	}
	return *o.Canonicalize
}

// GetCanonicalizeOk returns a tuple with the Canonicalize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemSetacl0Options) GetCanonicalizeOk() (*bool, bool) {
	if o == nil || o.Canonicalize == nil {
		return nil, false
	}
	return o.Canonicalize, true
}

// HasCanonicalize returns a boolean if a field has been set.
func (o *FilesystemSetacl0Options) HasCanonicalize() bool {
	if o != nil && o.Canonicalize != nil {
		return true
	}

	return false
}

// SetCanonicalize gets a reference to the given bool and assigns it to the Canonicalize field.
func (o *FilesystemSetacl0Options) SetCanonicalize(v bool) {
	o.Canonicalize = &v
}

func (o FilesystemSetacl0Options) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Stripacl != nil {
		toSerialize["stripacl"] = o.Stripacl
	}
	if o.Recursive != nil {
		toSerialize["recursive"] = o.Recursive
	}
	if o.Traverse != nil {
		toSerialize["traverse"] = o.Traverse
	}
	if o.Canonicalize != nil {
		toSerialize["canonicalize"] = o.Canonicalize
	}
	return json.Marshal(toSerialize)
}

type NullableFilesystemSetacl0Options struct {
	value *FilesystemSetacl0Options
	isSet bool
}

func (v NullableFilesystemSetacl0Options) Get() *FilesystemSetacl0Options {
	return v.value
}

func (v *NullableFilesystemSetacl0Options) Set(val *FilesystemSetacl0Options) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesystemSetacl0Options) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesystemSetacl0Options) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesystemSetacl0Options(val *FilesystemSetacl0Options) *NullableFilesystemSetacl0Options {
	return &NullableFilesystemSetacl0Options{value: val, isSet: true}
}

func (v NullableFilesystemSetacl0Options) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesystemSetacl0Options) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


